### ISSUE TITLE
[BUG] "主页" 翻译建议

### ISSUE THREAD

**Issue by longpoxin** [gdsub/atdocs#117]
# URL: https://atdocs.cn
## 建议1
> Build connected devices for a wide variety of consumer, retail, and industrial applications
* 当前译文: 为广大消费者、零售业和工业界构建物联网设备
* 建议译文: 为各种消费类、零售类和工业类应用构建物联网设备
## 建议2
> Leverage existing Android development tools, APIs, resources, and a thriving developer community.
* 当前译文: 完善的 Android 开发工具、应用程序接口、资源，以及不断发展的开发者社区，助您的开发事半功倍。
* 建议译文: 可以利用已有的Android开发工具、应用程序接口、资源，以及不断发展的开发者社区
## 建议3
> Rapid prototypes to real products
* 当前译文: 让您的产品从零到一
* 建议译文: 快速从原型到真正的产品
## 建议4
> Anyone, from startups to large companies, can build commercial products at scale
* 当前译文: 任何人，都可以从这里起步，构建您自己的物联网产品帝国
* 建议译文: 从初创公司到大型企业，任何人都可以构建一定规模的商业级产品
## 建议5
> Turnkey hardware solutions
* 当前译文: 一站式解决方案
* 建议译文: 完备的硬件平台解决方案
## 建议6
> Our certified development boards include the System on Chip (SoC), RAM, wireless radios, and more to get you started quickly.
* 当前译文: 经我们认证过的开发板包含 SoC 芯片，RAM，无线接收装置等，方便您快速开始构建您的应用。
* 建议译文: 我们认证的开发板，包含了片上系统（Soc）、RAM、无线模块，以及其他帮助您快速开始的组件。
## 建议7
> Build products at scale
* 当前译文: 更容易量产
* 建议译文: 构建一定规模的产品
## 建议8
> The power of Google at your fingertips
* 当前译文: Google 的强力驱动 您触手可及
* 建议译文: Google的力量触手可及
## 建议9
> Build and manage millions of devices at Google’s scale
* 当前译文: 使用 Google 的架构管理您的设备
* 建议译文: 用Google的框架来构建和管理数百万台设备

**Comment by YuchengWang** [comment]
谢谢您的建议。您的译文特别好，所有的信息已经更新。
